spring:
  application:
    name: ms-customer
  zipkin:
    base-url: '{cipher}f86a52b9b7f00558a0aaae4f87477834d5b7a5db5331d0901f38e6139a80ab385df95c1cb26ebc313d35ec059957413a779f1e6567096f474dfba0a93cd6fe70'
  h2:
    console:
      enabled: true
server:
  port: 6945

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: '{cipher}96990740eaf8b384c0d249df7a09a209c91e8e4d8c1b7783ef6768331139345d84bf91c8fc316dc268b85b0c91e1f6057da3dec666da3820fdcdf52fc93ac6e4'

management:
  endpoints:
    shutdown:
      enabled: true
      sensitive: false
