server:
  port: '{cipher}b86616c8a13c2551d8a87945274d4a2917a729ca0db7cd3d401ef25bd91763f8'
spring:
  application:
    name: '{cipher}a5e7edf54e7284824854d1a00a27e6d163dbbf9f8979713a835e9095ebd0135d'
  zipkin:
    base-url: '{cipher}7e1551bfc25422bddbf68b61c8576ccbb46debe353306b9ba8c166c80c727d71c925847e36884d301892847a003d301fd2677faf1b1a73695f7652c8723b9531'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: '{cipher}156ec6d3097728ca4e2712e94f16eab84c90c0350b2bc818e08c9e31215ea03ef54109d545a3d9fc22d2289054bb04f736ff5c3d0472a65989d921219f4085a6'
management:
  endpoints:
    web:
      exposure:
        include: "*"
