spring:
  application:
    name: ms-sale
  zipkin:
    base-url: http://localhost:9411
  h2:
    console:
      enabled: true
server:
  port: 8743

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka

management:
  endpoints:
    shutdown:
      enabled: true
      sensitive: false
